apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ui-app
  namespace: argocd
spec:
  project: todo-project
  
  source:
    repoURL: 'https://github.com/Prashantji007/MicrotodoUI'
    targetRevision: main
    path: /Helm/UI-Task/templates

    helm:
      valueFiles:
        - dev-values.yaml   # <-- tumhara values file yahi hai

  destination:
    server: https://kubernetes.default.svc
    namespace: app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
