apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: todo-project
  namespace: argocd
spec:
  description: Project for todo application
  sourceRepos:
    - '*'              # allow any Git repo
  destinations:
    - namespace: app
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
