# ---------------------------------------------------------
# todo APP
# ---------------------------------------------------------
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
spec:
  project: todo-project
  
  source:
    repoURL: https://github.com/Prashantji007/Gitops_setup_using_ArgoCD_Helm
    path: Helm
    targetRevision: main
    helm:
      valueFiles:
        - dev-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


