apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ui-app
  namespace: argocd
spec:
  project: todo-project
  
  source:
    repoURL: 'oci://acrtodoappdev01.azurecr.io/helm'
    chart: UI-Task
    targetRevision: 1.0.*

    helm:
      valueFiles:
        - dev-values.yaml   # <-- tumhara values file yahi hai

  destination:
    server: https://kubernetes.default.svc
    namespace: app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: add-task-app
  namespace: argocd
spec:
  project: todo-project
  
  source:
    repoURL: 'oci://acrtodoappdev01.azurecr.io/helm'
    chart: Add-Task
    targetRevision: 1.0.*

    helm:
      valueFiles:
        - dev-values.yaml   # <-- tumhara values file yahi hai

  destination:
    server: https://kubernetes.default.svc
    namespace: app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: delete-task-app
  namespace: argocd
spec:
  project: todo-project
  
  source:
    repoURL: 'oci://acrtodoappdev01.azurecr.io/helm'
    chart: Delete-Task
    targetRevision: 1.0.*

    helm:
      valueFiles:
        - dev-values.yaml   # <-- tumhara values file yahi hai

  destination:
    server: https://kubernetes.default.svc
    namespace: app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: get-task-app
  namespace: argocd
spec:
  project: todo-project
  
  source:
    repoURL: 'oci://acrtodoappdev01.azurecr.io/helm'
    chart: Get-Task
    targetRevision: 1.0.*

    helm:
      valueFiles:
        - dev-values.yaml   # <-- tumhara values file yahi hai

  destination:
    server: https://kubernetes.default.svc
    namespace: app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

